spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-group
      topic: wikimedia_recent_change
      auto-offset-reset: earliest

  data:
    mongodb:
      host: localhost
      port: 27017
      database: wikimedia
      uri: mongodb://localhost:27017/wikimedia

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
      show_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=wikimedia;encrypt=true;trustServerCertificate=true
    username: sa
    password: '@Potter77'